apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azure-metrics-exporter.fullname" . }}
  labels:
    {{- include "azure-metrics-exporter.labels" . | nindent 4 }}
data:
  azure.yml: |-
    credentials:
      subscription_id: {{ .Values.subscriptionId }}
    {{- toYaml .Values.config | nindent 4 }}
