replicaCount: 1

podidentity: ""

image:
  repository: robustperception/azure_metrics_exporter
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9276

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# NOTE : Azure imposes an API read limit of 15,000 requests per hour so the number of metrics you're querying for should be proportional to your scrape interval.
scrapeInterval: 30s

subscriptionId: ""

# NOTE : azure_resource_id should start with /resourceGroups... (/subscriptions/xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxx must be removed from the begining of azure_resource_id property value)
config: {}
  # targets:
  #   - resource: "azure_resource_id"
  #     metrics:
  #     - name: "BytesReceived"
  #     - name: "BytesSent"
  #   - resource: "azure_resource_id"
  #     aggregations:
  #     - Minimum
  #     - Maximum
  #     - Average
  #     metrics:
  #     - name: "Http2xx"
  #     - name: "Http5xx"
  #   - resource: "azure_resource_id"
  #     metric_namespace: "Azure.VM.Windows.GuestMetrics"
  #     metrics:
  #     - name: 'Process\Thread Count'

  # resource_groups:
  #   - resource_group: "webapps"
  #     resource_types:
  #     - "Microsoft.Compute/virtualMachines"
  #     resource_name_include_re:
  #     - "testvm.*"
  #     resource_name_exclude_re:
  #     - "testvm12"
  #     metrics:
  #     - name: "CPU Credits Consumed"

  # resource_tags:
  #   - resource_tag_name: "group"
  #     resource_tag_value: "tomonitor"
  #     resource_types:
  #       - "Microsoft.Compute/virtualMachines"
  #     metrics:
  #       - name: "CPU Credits Consumed"
